# Generated by Django 2.2.17 on 2020-11-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
