# Generated by Django 2.2.17 on 2020-11-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default=True, max_length=300),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
